In [396]:
# package imports
import numpy as np
from itertools import islice
from scipy.linalg import eig
from scipy.stats import norm
import pandas as pd

In [397]:
# get stationary dustribution of transition matrix
# from stack overflow
def get_stationary_distibution(state_transition_matrix: np.ndarray) -> np.ndarray:
    S, U = eig(state_transition_matrix.T)
    stationary = np.array(U[:, np.where(np.abs(S - 1.) < 1e-8)[0][0]].flat)
    stationary = stationary / np.sum(stationary)
    return stationary

In [398]:
def estimate_sequence(state_transition_matrix:np.ndarray, gaussian_params: np.ndarray, initial_state_probability:np.ndarray, observations:np.ndarray, state_count: int):
    observation_count = observations.shape[0]
    state_probability_matrix = np.zeros((state_count, observation_count))
    cond_prob = norm.pdf(observations[0], loc=gaussian_params[:,0], scale=gaussian_params[:,1])
    state_probability_matrix[:,0] = np.log2(state_transition_matrix[:,0] * cond_prob)
    path = np.zeros((1,observation_count))
    for i in range(1, observation_count):
        cond_prob = norm.pdf(observations[i], loc=gaussian_params[:,0], scale=gaussian_params[:,1])
        for j in range(state_count):
            prob = state_probability_matrix[:,i-1] + np.log2(transition_matrix[:,j]) + np.log2(cond_prob[j])
            path[0,i] = np.argmax(prob)
            state_probability_matrix[j,i] = max(prob)

    return path, state_probability_matrix
    # for i in range(1, observation_count):
    # cond_prob = norm.pdf(observations[1], loc=gaussian_params[:,0], scale=gaussian_params[:,1])
    # state_probability_matrix[0,1] = max(state_probability_matrix[:,0] + np.log2(transition_matrix[:,0]) + np.log2(cond_prob[0]))
    # state_probability_matrix[1,1] = max(state_probability_matrix[:,0] + np.log2(transition_matrix[:,1]) + np.log2(cond_prob[1]))
    # print(state_probability_matrix[:,1])
    # state_probability_matrix[:,1] = max(state_probability_matrix[:,0] + np.log2(transition_matrix) + np.log2(cond_prob))
    # print(state_probability_matrix[:,1])

In [399]:
# Viterbi algorithm
def viterbi():
    pass

In [400]:
# Baum-Welch Learning
def baum_welch():
    pass

In [401]:
# read data
observed_states = np.loadtxt('./Input/data.txt', dtype=float)
observed_states.shape

(1000,)

In [402]:
# read parameters
with open('./Input/parameters.txt.txt', 'r') as f:
    no_of_states = int(f.readline())

with open('./Input/parameters.txt.txt', 'r') as lines:
    transition_matrix = np.genfromtxt(islice(lines, 1, 1+no_of_states))

with open('./Input/parameters.txt.txt', 'r') as lines:
    gaussian_parameters = np.genfromtxt(islice(lines, 1+no_of_states, 1+2*no_of_states), dtype=int)

gaussian_parameters

array([[200, 100],
       [ 10,  10]])

In [403]:
initial_distribution = get_stationary_distibution(transition_matrix)
initial_distribution

array([0.25, 0.75])

In [404]:
a, b = estimate_sequence(transition_matrix, gaussian_parameters, initial_distribution.T, observed_states, no_of_states)

In [405]:
# norm.pdf(104.524317662043, loc=gaussian_parameters[:,0], scale=gaussian_parameters[:,1])
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 

In [406]:
b

array([[   -9.1417294 ,   -18.37205626,   -27.5603542 , ...,
        -8883.53784543, -8892.80059646, -8902.02466763],
       [  -72.42089887,   -71.76317252,   -84.75605644, ...,
        -9020.41398894, -8943.40878121, -8955.96759007]])